name: Ruff
on:
  push:
    paths:
      - 'tofuref/**'
      - 'tests/**'
      - 'helpers/**'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'tofuref/**'
      - 'tests/**'
      - 'helpers/**'
      - 'pyproject.toml'

permissions:
  contents: read # needed for actions/checkout

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
