name: Ruff
on: [ push, pull_request ]

permissions:
  contents: read # needed for actions/checkout

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
